services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: books_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
      - images:/app/api/parsing_json/images/
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  images:
