# Generated by Django 6.0.4 on 2026-04-25 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_subcategory', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('isbn', models.TextField(blank=True, null=True)),
                ('pagecount', models.IntegerField(blank=True, null=True)),
                ('publisheddate', models.TextField(blank=True, null=True)),
                ('thumbnailurl', models.TextField(blank=True, null=True)),
                ('shortdescription', models.TextField(blank=True, null=True)),
                ('longdescription', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='authors_book', to='api.author')),
                ('categories', models.ManyToManyField(blank=True, related_name='categories_book', to='api.category')),
                ('subcategories', models.ManyToManyField(blank=True, related_name='subcategories_book', to='api.subcategory')),
            ],
        ),
    ]
